package:
  name: uproc
  version: "1.2.0"

source:
  url: http://uproc.gobics.de/downloads/uproc/uproc-1.2.0-win-x86_64.zip  # [win64]
  url: http://uproc.gobics.de/downloads/uproc/uproc-1.2.0-win-i686.zip    # [win32]
  url: http://uproc.gobics.de/downloads/uproc/uproc-1.2.0.tar.gz          # [not win]

requirements:
  build:
    - make          # [not win]
    - gcc_linux-64  # [linux64]
    - libgcc        # [osx]
    - zlib          # [not win]

test:
  commands:
    - uproc-prot -h      # [not win]
    - uproc-prot -h  # [win]

about:
  home: http://uproc.gobics.de
