package:
  name: uproc
  version: "1.2.0"

source:
  url: http://uproc.gobics.de/downloads/uproc/uproc-1.2.0.tar.gz          # [not win]
  url: http://uproc.gobics.de/downloads/uproc/uproc-1.2.0-win-x86_64.zip  # [win64]
  url: http://uproc.gobics.de/downloads/uproc/uproc-1.2.0-win-i686.zip    # [win32]
  folder: src                                                             # [win]

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - make                 # [not win]
    - zlib                 # [not win]
    - llvm-openmp          # [osx]
  host:
    - zlib
    - llvm-openmp          # [osx]
  run:
    - zlib
    - llvm-openmp          # [osx]

test:
  commands:
    - uproc-prot   -V  # [not win]
    - uproc-prot   -v  # [not win]
    - uproc-dna    -v  # [not win]
    - uproc-orf    -v  # [not win]
    - uproc-import -v  # [not win]
    - uproc-export -v  # [not win]
    - uproc-makedb -v  # [not win]
    
    - uproc-prot   -V  # [win]
    - uproc-prot.exe   -v  # [win]
    - uproc-dna.exe    -v  # [win]
    - uproc-orf.exe    -v  # [win]
    - uproc-import.exe -v  # [win]
    - uproc-export.exe -v  # [win]
    - uproc-makedb.exe -v  # [win]

about:
  home: http://uproc.gobics.de
  summary: UProC - tools for ultra-fast protein sequence classification
  license: GNU GPLv3
  license_file: COPYING
