package:
  name: uproc
  version: "1.2.0"

source:
  url: http://uproc.gobics.de/downloads/uproc/uproc-1.2.0.tar.gz          # [not win]
  url: http://uproc.gobics.de/downloads/uproc/uproc-1.2.0-win-x86_64.zip  # [win64]
  url: http://uproc.gobics.de/downloads/uproc/uproc-1.2.0-win-i686.zip    # [win32]
  folder: src                                                             # [win]

requirements:
  build:
    #- gcc_linux-64  # [linux64]
    - libgcc        # [osx]
    #- {{ compiler('c') }}  # [not win]
    - make          # [not win]
    - zlib          # [not win]
    - llvm-openmp        # [osx]
  host:
    - zlib
    - openmp
  run:
    - zlib
    - openmp

test:
  commands:
    - uproc-prot -V      # [not win]
    - uproc-prot.exe -V  # [win]

about:
  home: http://uproc.gobics.de
