name: Conda

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install build dependencies
        run: conda install conda-build anaconda-client

      - name: Create build dir
        run: mkdir build

      - name: Build package
        run: conda build --output-folder build .

      - name: Upload package
        run: anaconda upload build/linux-64/uproc*.tar.bz2
